Import necessary libraries

In [1]:
import pandas as pd
import numpy as np

**1.** Fetch dataset. In order to have possibility to fetch it by URL, I have uploaded dataset to my GitHub.

Dataset is about aid from different countries for Ukraine. Original dataset is taken from https://www.kaggle.com/datasets/jainaru/financial-aid-to-ukraine.

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/YaroslavDrovolskyi/applied-application-of-neural-networks/main/lab1/Financial%20Allocations.csv")

**2.** Print dataset

In [3]:
df

,Country,EU member,Financial allocations($ billion),Humanitarian allocations($ billion),Military allocations($ billion),Share in EU allocations($ billion)
0,Australia,0,0.728552,0.069499,0.003587,0.140745
1,Austria,1,0.191309,0.053399,0.923287,0.000000
2,Belgium,1,0.000000,0.001041,0.262288,0.120810
3,Bulgaria,1,3.695839,0.397457,NaN,0.052599
4,Canada,0,0.000000,0.086783,0.203566,0.486123
5,Croatia,1,0.001071,0.003214,0.000000,0.677306
6,Cyprus,1,0.000000,0.057240,1.378977,0.066770
7,Czech Republic,1,0.131348,0.261334,5.116618,0.000000
8,Denmark,1,0.000000,0.052539,0.524732,0.556736
9,Estonia,1,29.656888,2.449756,0.000000,5.689608
10,Finland,1,0.856477,0.387744,2.883296,0.397497
11,France,1,1.507460,3.263849,10.752226,0.311993
12,Germany,1,0.000000,0.000000,0.143237,0.000000
13,Greece,1,0.000000,0.057910,0.000000,0.571627
14,Hungary,1,0.010197,0.011962,0.017934,3.986497
15,Iceland,0,0.042856,0.060264,0.004125,0.000000
16,Ireland,1,0.439274,0.345916,1.071400,0.068451
17,Italy,1,5.180550,1.094119,0.069452,0.107600
18,Japan,0,0.043927,0.008164,0.403534,0.093190
19,Latvia,1,0.044463,NaN,0.694695,0.028101
20,Lithuania,1,0.001393,0.019430,0.171816,1.404088
21,Luxembourg,1,0.000000,0.002218,0.000000,0.000000
22,Malta,1,0.766694,0.606725,4.121160,0.000000
23,Netherlands,1,0.001824,0.027791,0.020944,1.172315
24,New Zealand,0,0.826775,0.374528,0.900321,0.482520
25,Norway,0,1.013623,0.405961,3.214200,0.000000
26,Poland,1,0.000000,0.001834,0.078204,0.492848
27,Portugal,1,0.310000,0.292000,NaN,0.210637
28,South Korea,0,0.000000,0.130651,0.004444,0.109762
29,Romania,1,0.005357,0.011832,0.720195,2.651580
30,Slovakia,1,0.000000,0.015449,0.069332,0.984015
31,Slovenia,1,0.556807,0.090665,0.348613,0.000000
32,Spain,1,0.367611,0.173441,2.938226,0.000000
33,Sweden,1,0.110382,0.741076,0.000000,0.000000
34,Switzerland,0,0.000000,0.005012,0.067094,0.000000
35,Turkey,0,3.510938,0.588998,5.641805,0.000000
36,United Kingdom,0,23.000000,2.706826,46.152000,0.000000
37,United States,0,0.000000,0.002284,0.000000,0.000000
38,China,0,0.000000,0.029170,0.000000,NaN
39,Taiwan,0,0.000000,0.002169,0.000000,NaN
40,India,0,NaN,NaN,NaN,NaN

**3.** Check if any value in dataframe is `NaN`.

In [4]:
df.isnull().any().any()

True

**4.** Dataset has `NaN` values, so need to replace them by `10`. Print dataset with replaces `NaN`s

In [5]:
df.fillna(10)

,Country,EU member,Financial allocations($ billion),Humanitarian allocations($ billion),Military allocations($ billion),Share in EU allocations($ billion)
0,Australia,0,0.728552,0.069499,0.003587,0.140745
1,Austria,1,0.191309,0.053399,0.923287,0.000000
2,Belgium,1,0.000000,0.001041,0.262288,0.120810
3,Bulgaria,1,3.695839,0.397457,10.000000,0.052599
4,Canada,0,0.000000,0.086783,0.203566,0.486123
5,Croatia,1,0.001071,0.003214,0.000000,0.677306
6,Cyprus,1,0.000000,0.057240,1.378977,0.066770
7,Czech Republic,1,0.131348,0.261334,5.116618,0.000000
8,Denmark,1,0.000000,0.052539,0.524732,0.556736
9,Estonia,1,29.656888,2.449756,0.000000,5.689608
10,Finland,1,0.856477,0.387744,2.883296,0.397497
11,France,1,1.507460,3.263849,10.752226,0.311993
12,Germany,1,0.000000,0.000000,0.143237,0.000000
13,Greece,1,0.000000,0.057910,0.000000,0.571627
14,Hungary,1,0.010197,0.011962,0.017934,3.986497
15,Iceland,0,0.042856,0.060264,0.004125,0.000000
16,Ireland,1,0.439274,0.345916,1.071400,0.068451
17,Italy,1,5.180550,1.094119,0.069452,0.107600
18,Japan,0,0.043927,0.008164,0.403534,0.093190
19,Latvia,1,0.044463,10.000000,0.694695,0.028101
20,Lithuania,1,0.001393,0.019430,0.171816,1.404088
21,Luxembourg,1,0.000000,0.002218,0.000000,0.000000
22,Malta,1,0.766694,0.606725,4.121160,0.000000
23,Netherlands,1,0.001824,0.027791,0.020944,1.172315
24,New Zealand,0,0.826775,0.374528,0.900321,0.482520
25,Norway,0,1.013623,0.405961,3.214200,0.000000
26,Poland,1,0.000000,0.001834,0.078204,0.492848
27,Portugal,1,0.310000,0.292000,10.000000,0.210637
28,South Korea,0,0.000000,0.130651,0.004444,0.109762
29,Romania,1,0.005357,0.011832,0.720195,2.651580
30,Slovakia,1,0.000000,0.015449,0.069332,0.984015
31,Slovenia,1,0.556807,0.090665,0.348613,0.000000
32,Spain,1,0.367611,0.173441,2.938226,0.000000
33,Sweden,1,0.110382,0.741076,0.000000,0.000000
34,Switzerland,0,0.000000,0.005012,0.067094,0.000000
35,Turkey,0,3.510938,0.588998,5.641805,0.000000
36,United Kingdom,0,23.000000,2.706826,46.152000,0.000000
37,United States,0,0.000000,0.002284,0.000000,0.000000
38,China,0,0.000000,0.029170,0.000000,10.000000
39,Taiwan,0,0.000000,0.002169,0.000000,10.000000
40,India,0,10.000000,10.000000,10.000000,10.000000

**5.** Delete rows with `NaN` values. (Drop the rows where at least one element is `NaN`).

In [6]:
df=df.dropna()
df

,Country,EU member,Financial allocations($ billion),Humanitarian allocations($ billion),Military allocations($ billion),Share in EU allocations($ billion)
0,Australia,0,0.728552,0.069499,0.003587,0.140745
1,Austria,1,0.191309,0.053399,0.923287,0.000000
2,Belgium,1,0.000000,0.001041,0.262288,0.120810
4,Canada,0,0.000000,0.086783,0.203566,0.486123
5,Croatia,1,0.001071,0.003214,0.000000,0.677306
6,Cyprus,1,0.000000,0.057240,1.378977,0.066770
7,Czech Republic,1,0.131348,0.261334,5.116618,0.000000
8,Denmark,1,0.000000,0.052539,0.524732,0.556736
9,Estonia,1,29.656888,2.449756,0.000000,5.689608
10,Finland,1,0.856477,0.387744,2.883296,0.397497
11,France,1,1.507460,3.263849,10.752226,0.311993
12,Germany,1,0.000000,0.000000,0.143237,0.000000
13,Greece,1,0.000000,0.057910,0.000000,0.571627
14,Hungary,1,0.010197,0.011962,0.017934,3.986497
15,Iceland,0,0.042856,0.060264,0.004125,0.000000
16,Ireland,1,0.439274,0.345916,1.071400,0.068451
17,Italy,1,5.180550,1.094119,0.069452,0.107600
18,Japan,0,0.043927,0.008164,0.403534,0.093190
20,Lithuania,1,0.001393,0.019430,0.171816,1.404088
21,Luxembourg,1,0.000000,0.002218,0.000000,0.000000
22,Malta,1,0.766694,0.606725,4.121160,0.000000
23,Netherlands,1,0.001824,0.027791,0.020944,1.172315
24,New Zealand,0,0.826775,0.374528,0.900321,0.482520
25,Norway,0,1.013623,0.405961,3.214200,0.000000
26,Poland,1,0.000000,0.001834,0.078204,0.492848
28,South Korea,0,0.000000,0.130651,0.004444,0.109762
29,Romania,1,0.005357,0.011832,0.720195,2.651580
30,Slovakia,1,0.000000,0.015449,0.069332,0.984015
31,Slovenia,1,0.556807,0.090665,0.348613,0.000000
32,Spain,1,0.367611,0.173441,2.938226,0.000000
33,Sweden,1,0.110382,0.741076,0.000000,0.000000
34,Switzerland,0,0.000000,0.005012,0.067094,0.000000
35,Turkey,0,3.510938,0.588998,5.641805,0.000000
36,United Kingdom,0,23.000000,2.706826,46.152000,0.000000
37,United States,0,0.000000,0.002284,0.000000,0.000000

**6.** Create new column ('Total allocations')  as a sum of three existing columns

In [8]:
df.loc[:, 'Total allocations'] = df['Financial allocations($ billion)'] + df['Humanitarian allocations($ billion)'] + df['Military allocations($ billion)']

In [9]:
df

,Country,EU member,Financial allocations($ billion),Humanitarian allocations($ billion),Military allocations($ billion),Share in EU allocations($ billion),Total allocations
0,Australia,0,0.728552,0.069499,0.003587,0.140745,0.801638
1,Austria,1,0.191309,0.053399,0.923287,0.000000,1.167995
2,Belgium,1,0.000000,0.001041,0.262288,0.120810,0.263330
4,Canada,0,0.000000,0.086783,0.203566,0.486123,0.290349
5,Croatia,1,0.001071,0.003214,0.000000,0.677306,0.004286
6,Cyprus,1,0.000000,0.057240,1.378977,0.066770,1.436216
7,Czech Republic,1,0.131348,0.261334,5.116618,0.000000,5.509301
8,Denmark,1,0.000000,0.052539,0.524732,0.556736,0.577272
9,Estonia,1,29.656888,2.449756,0.000000,5.689608,32.106644
10,Finland,1,0.856477,0.387744,2.883296,0.397497,4.127517
11,France,1,1.507460,3.263849,10.752226,0.311993,15.523534
12,Germany,1,0.000000,0.000000,0.143237,0.000000,0.143237
13,Greece,1,0.000000,0.057910,0.000000,0.571627,0.057910
14,Hungary,1,0.010197,0.011962,0.017934,3.986497,0.040093
15,Iceland,0,0.042856,0.060264,0.004125,0.000000,0.107245
16,Ireland,1,0.439274,0.345916,1.071400,0.068451,1.856590
17,Italy,1,5.180550,1.094119,0.069452,0.107600,6.344121
18,Japan,0,0.043927,0.008164,0.403534,0.093190,0.455625
20,Lithuania,1,0.001393,0.019430,0.171816,1.404088,0.192638
21,Luxembourg,1,0.000000,0.002218,0.000000,0.000000,0.002218
22,Malta,1,0.766694,0.606725,4.121160,0.000000,5.494580
23,Netherlands,1,0.001824,0.027791,0.020944,1.172315,0.050560
24,New Zealand,0,0.826775,0.374528,0.900321,0.482520,2.101624
25,Norway,0,1.013623,0.405961,3.214200,0.000000,4.633784
26,Poland,1,0.000000,0.001834,0.078204,0.492848,0.080038
28,South Korea,0,0.000000,0.130651,0.004444,0.109762,0.135095
29,Romania,1,0.005357,0.011832,0.720195,2.651580,0.737384
30,Slovakia,1,0.000000,0.015449,0.069332,0.984015,0.084781
31,Slovenia,1,0.556807,0.090665,0.348613,0.000000,0.996085
32,Spain,1,0.367611,0.173441,2.938226,0.000000,3.479278
33,Sweden,1,0.110382,0.741076,0.000000,0.000000,0.851458
34,Switzerland,0,0.000000,0.005012,0.067094,0.000000,0.072106
35,Turkey,0,3.510938,0.588998,5.641805,0.000000,9.741742
36,United Kingdom,0,23.000000,2.706826,46.152000,0.000000,71.858826
37,United States,0,0.000000,0.002284,0.000000,0.000000,0.002284

**7.** Make generalized description of dataset

In [10]:
df.describe()

,EU member,Financial allocations($ billion),Humanitarian allocations($ billion),Military allocations($ billion),Share in EU allocations($ billion),Total allocations
count,35.000000,35.000000,35.000000,35.000000,35.000000,35.000000
mean,0.685714,1.970037,0.404842,2.520189,0.587774,4.895068
std,0.471008,6.227082,0.793996,7.917894,1.208496,13.126261
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.002218
25%,0.000000,0.000000,0.011897,0.011189,0.000000,0.096013
50%,1.000000,0.042856,0.060264,0.203566,0.107600,0.737384
75%,1.000000,0.747623,0.381136,1.225188,0.524792,3.803397
max,1.000000,29.656888,3.263849,46.152000,5.689608,71.858826

As we see, each country, **on average**, has allocated 4.895068 bn USD for Ukraine as support.

Minimum donation is 0.002218 bn USD, maximal is 71.858826 bn USD.

**8.** Make analysis for EU and non-EU countries

In [20]:
df.groupby(['EU member']).agg({'Financial allocations($ billion)':[min, max, sum, 'mean'],
                               'Humanitarian allocations($ billion)':[min, max, sum, 'mean'],
                               'Military allocations($ billion)':[min, max, sum, 'mean'],
                               'Total allocations':[min, max, sum, 'mean']})

<ipython-input-20-f7d240ff313c>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(['EU member']).agg({'Financial allocations($ billion)':[min, max, sum, 'mean'],
<ipython-input-20-f7d240ff313c>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby(['EU member']).agg({'Financial allocations($ billion)':[min, max, sum, 'mean'],
<ipython-input-20-f7d240ff313c>:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby(['EU member']).agg({'Financial allocations($ billion)':[min, max, sum, 'mean'],

          Financial allocations($ billion)                                  \
                                       min        max        sum      mean
EU member
0                                      0.0  23.000000  29.166671  2.651516
1                                      0.0  29.656888  39.784641  1.657693

          Humanitarian allocations($ billion)                                \
                                          min       max       sum      mean
EU member
0                                    0.002284  2.706826  4.438970  0.403543
1                                    0.000000  3.263849  9.730485  0.405437

          Military allocations($ billion)                                  \
                                      min        max        sum      mean
EU member
0                                     0.0  46.152000  56.594677  5.144971
1                                     0.0  10.752226  31.611938  1.317164

          Total allocations
                        min        max        sum      mean
EU member
0                  0.002284  71.858826  90.200317  8.200029
1                  0.002218  32.106644  81.127064  3.380294

As we see, average non-EU country has donated 8.2 bn USD for Ukraine, and average EU country - 3.38 bn USD.

Minimum not-EU country allocation is 0.002284 bn USD, maximal is 71.858826 bn USD.
Minimum EU country allocation is 0.002218 bn USD, maximal is 32.106644 bn USD.

So, EU countries have allocated 81.12 bn USD, but not-EU countries - 90.2 bn USD.